import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const u32=n=>{const b=Buffer.alloc(4);b.writeUInt32BE(n);return b},u64=n=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(n));return b};
const frame=(p,b)=>{const pb=Buffer.from(p);return Buffer.concat([u32(pb.length),pb,u64(b.length),crypto.createHash('sha256').update(b).digest()])};
const read=p=>fs.readFileSync(path.join(root,p)),json=p=>JSON.parse(read(p));
const eq=(a,b,msg)=>{if(a!==b)throw Error(msg)};
const exact=(a,b,msg)=>{if(a.length!==b.length||[...a].sort().join('\0')!==[...b].sort().join('\0'))throw Error(msg)};
const auditIds=['P1-01','P1-02','P1-03','P1-04','P1-05','P1-06','P1-07','P1-08','P2-01','NEW-P1-01','NEW-P1-02','NEW-P1-03','NEW-P1-04'];
function allFiles(dir,prefix=''){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?allFiles(path.join(dir,x.name),`${prefix}${x.name}/`):[`${prefix}${x.name}`])}
function safe(p){if(!p||p!==p.normalize('NFC')||p.includes('\\')||p.includes(':')||p.startsWith('/')||p.includes('\0'))return false;const bad=new Set(['CON','PRN','AUX','NUL','COM1','COM2','COM3','COM4','COM5','COM6','COM7','COM8','COM9','LPT1','LPT2','LPT3','LPT4','LPT5','LPT6','LPT7','LPT8','LPT9']);return p.split('/').every(x=>x&&x!=='.'&&x!=='..'&&!/[ .]$/.test(x)&&!bad.has(x.split('.')[0].toUpperCase()))}
function textOk(b){if(b[0]===0xef&&b[1]===0xbb&&b[2]===0xbf)return false;const s=b.toString('utf8');return Buffer.from(s).compare(b)===0&&!s.includes('\r')&&!s.includes('\0')&&s.endsWith('\n')&&!s.endsWith('\n\n')}
function verify(){
 const m=json('17_INTEGRATION_DRAFT_MANIFEST.json');eq(m.state,'DRAFT_PREFREEZE','state');eq(m.authority_state,'PENDING_OWNER_SUPERSESSION','authority');
 const paths=m.entries.map(x=>x.path);if(new Set(paths).size!==paths.length||paths.some(x=>!safe(x)))throw Error('paths');
 for(const norm of [x=>x.normalize('NFC'),x=>x.normalize('NFD'),x=>x.toLocaleLowerCase('en-US')])if(new Set(paths.map(norm)).size!==paths.length)throw Error('collision');
 const detached=new Set(['17_INTEGRATION_DRAFT_MANIFEST.json',...m.detached_allowlist]);
 const actual=allFiles(root).filter(x=>!detached.has(x));exact(actual,paths,'actual exact set');
 for(const e of m.entries){const p=path.join(root,...e.path.split('/')),st=fs.lstatSync(p),b=fs.readFileSync(p);if(st.isSymbolicLink()||st.nlink!==1)throw Error('physical');eq(b.length,e.bytes,`bytes ${e.path}`);eq(sha(b),e.sha256,`hash ${e.path}`);if(/\.(json|md|mjs|py|ps1|txt)$/.test(e.path)&&!textOk(b))throw Error(`encoding ${e.path}`)}
 const collector=path.join(root,'28_WINDOWS_PATH_CUSTODY_COLLECTOR.ps1');for(const relativePath of paths){const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',collector,'-Root',root,'-RelativePath',relativePath],{encoding:'utf8'});if(r.status!==0)throw Error(`path collector ${relativePath}: ${r.stderr||r.stdout}`)}
 const plan=read('Inputs/CANONICAL_PLAN.md');eq(plan.length,m.plan.bytes,'plan bytes');eq(sha(plan),m.plan.sha256,'plan hash');
 const ce=m.content_set.entries,content=sha(Buffer.concat([Buffer.from('N8NAGENTS-PLAN-V2-CONTENT-V3\0'),...ce.map(e=>frame(e.path,read(e.path)))]));eq(content,m.content_set.sha256,'content');
 const subjFiles=['14_REVIEW_SCHEMA_V2.json','23_QUORUM_SCHEMA_V2.json','20_PREFREEZE_CHECKER_NODE.mjs','21_PREFREEZE_CHECKER_PYTHON.py','25_RAW_REVIEW_BATCH_VALIDATOR_NODE.mjs','26_RAW_REVIEW_BATCH_VALIDATOR_PYTHON.py','28_WINDOWS_PATH_CUSTODY_COLLECTOR.ps1'];
 const subject=sha(Buffer.concat([Buffer.from('N8NAGENTS-PLAN-V2-REVIEW-SUBJECT-V3\0'),Buffer.from(content,'hex'),...subjFiles.map(p=>frame(p,read(p)))]));eq(subject,m.subject_envelope.sha256,'subject');exact(m.subject_envelope.source_paths,subjFiles,'subject files');
 const cap=json('33_INPUT_CAPTURE_INDEX.json');eq(cap.source_count,51,'inputs');for(const x of cap.captures){const b=read(x.capture_path);eq(b.length,x.bytes,'capture bytes');eq(sha(b),x.sha256,'capture hash')}eq(cap.canonical_plan.sha256,m.plan.sha256,'plan capture');
 const master=read('Inputs/N8N_AGENT_MASTER_PROMPT.md');eq(master.length,27410,'master bytes');eq(sha(master),'7b271daf6c3952aff905d2358e2e1a3c36ca789e5be784968311e133d1758da3','master hash');
 const audit=json('24_PROSPECTIVE_AUDIT_R2_BASELINE.json'),raw=read('Inputs/C2_PREFREEZE_AUDIT_R2_RAW.md');exact(audit.required_ids,auditIds,'audit ids');for(const id of auditIds){const x=audit.items[id],span=raw.subarray(x.source_span.offset,x.source_span.offset+x.source_span.bytes);eq(sha(span),x.source_span.sha256,`span ${id}`)}eq(audit.audited_subject.replay_state,'SOURCE_ASSERTED_NOT_REPLAYED','legacy replay');
 const ds=json('32_AUDIT_SUPERSESSION_DECISION_SET.json');eq(ds.authority_state,'PENDING_OWNER_SUPERSESSION','decision pending');eq(ds.quorum.valid_decisions,3,'decision count');eq(ds.quorum.approve_count,3,'decision approve');eq(new Set(Object.values(ds.decisions).map(x=>x.raw_sha256)).size,3,'decision hash unique');eq(ds.owner_activation_gate.status,'NOT_GRANTED','owner gate');
 const disp=json('07_FINDING_DISPOSITIONS_V2.json'),cl=json('08_CONSENSUS_CLOSURE_V2.json'),schema=json('14_REVIEW_SCHEMA_V2.json');eq(disp.findings.length,114,'findings');eq(cl.clusters.length,11,'clusters');eq(cl.cross_domain_decisions.decisions.length,15,'xd');eq(schema['x-exact-set-counts'].audit,13,'schema audit');exact(schema.properties.audit_assessments.required,auditIds,'schema audit ids');
 const at=json('09_ACCEPTANCE_TEST_CATALOG.json'),nc=json('10_NEGATIVE_CANARY_CATALOG.json'),ev=json('11_EVIDENCE_CATALOG.json');eq(at.tests.length,129,'AT');eq(nc.canaries.length,129,'NC');eq(ev.evidence.length,129,'EV');const banned=['SYNTHETIC_EXACT_POSITIVE','SYNTHETIC_EXACT_INTEGRATION','execute source procedure','positive boundary','<exact-fixture-path>','REQUIRED_EXACT_RUNTIME_VALUE','LOCKED_AMD64_IMAGE_DIGEST'];for(const f of ['09_ACCEPTANCE_TEST_CATALOG.json','10_NEGATIVE_CANARY_CATALOG.json','11_EVIDENCE_CATALOG.json'])for(const x of banned)if(read(f).includes(Buffer.from(x)))throw Error(`placeholder ${x}`);
 const alias=json('12_CANONICAL_ALIAS_MAP_V2.json').aliases.find(x=>x.alias_id==='EV-V3-ACL');eq(alias.disposition,'CANONICAL_MULTI_BINDING','acl');exact(alias.canonical_target_ids,['EV-F-R6-P1-001','EV-F-R3-CTRL-005','EV-F-R1-WIN-004'],'acl targets');eq(alias.join_semantics,'ALL_TARGETS_REQUIRED_SAME_RUN','acl run');
 const sm=json('18_CHILD_STATUS_MAPPING_V2.json'),keys=sm.mappings.map(x=>x.native_status_key).sort((a,b)=>Buffer.from(a).compare(Buffer.from(b)));eq(keys.length,306,'status count');eq(new Set(keys).size,306,'status unique');eq(sha(Buffer.from(keys.join('\n')+'\n')),'afd05d828c22c9132b7e00612781c776ddc922ea089c2a61cf14f1921e589c06','status keys');
 const top=json('31_EXECUTABLE_TOPOLOGY_R2.json');eq(top.long_running_services.length,8,'long services');eq(top.one_shot_services.length,15,'oneshot');if(!top.one_shot_services.includes('backup-verifier')||!top.modes['MOCK/RUN'].services.includes('telegram-bridge')||top.modes['MOCK/RUN'].services.includes('egress-telegram'))throw Error('topology');
 return true;
}
const mutationCases=[['CU-PLAN-HASH','plan_hash','STOP_PLAN_MISMATCH',21],['CU-PLAN-BYTES','plan_bytes','STOP_PLAN_MISMATCH',21],['CU-INPUT-HASH','input_hash','STOP_INPUT_MISMATCH',21],['CU-INPUT-COUNT','input_count','STOP_INPUT_MISMATCH',21],['CU-CONTENT','content','STOP_CONTENT_MISMATCH',21],['CU-SUBJECT','subject','STOP_SUBJECT_MISMATCH',22],['CU-MANIFEST-HASH','manifest_hash','STOP_MANIFEST_ENTRY_MISMATCH',21],['CU-MANIFEST-MISSING','manifest_missing','STOP_MANIFEST_ENTRY_MISMATCH',21],['CU-TRANSCRIPT','transcript','STOP_TRANSCRIPT_MISMATCH',22],['CU-ENCODING','encoding','STOP_ENCODING',20],['CU-SOURCE-HASH','source_hash','STOP_SOURCE_BINDING',21],['CU-SEVERITY','severity','STOP_DISPOSITION_MISMATCH',24],['CU-BLOCKING','blocking','STOP_DISPOSITION_MISMATCH',24],['CU-SECTION','section','STOP_SECTION_BINDING',24],['CU-AT','at','STOP_TEST_BINDING',24],['CU-NC','nc','STOP_CANARY_BINDING',24],['CU-EV','ev','STOP_EVIDENCE_BINDING',24],['CU-CLUSTER','cluster','STOP_CLUSTER_EXACTSET',24],['CU-BOILERPLATE','boilerplate','STOP_SEMANTIC_CONTRACT',24],['CU-ACL','acl','STOP_ALIAS_BINDING',24],['CU-HTTP-METHOD','http_method','STOP_HTTP_POLICY',51],['CU-HTTP-PATH','http_path','STOP_HTTP_POLICY',51],['CU-HTTP-BODY','http_body','STOP_HTTP_POLICY',51],['CU-HTTP-REDIRECT','http_redirect','STOP_HTTP_REDIRECT',42],['CU-SAME-BRIDGE','same_bridge','STOP_BRIDGE_IDENTITY',43],['CU-MOCK-SECRET','mock_secret','STOP_MOCK_CONTAMINATION',51],['CU-TOPOLOGY','topology','STOP_TOPOLOGY_EXACTSET',42],['CU-BACKUP-VERIFIER','backup_verifier','STOP_BACKUP_VERIFIER',42],['CU-BACKUP-KEY','backup_key','STOP_SECRET_BOUNDARY',51],['CU-STATUS-TUPLE','status_tuple','STOP_STATUS_MAPPING',52],['CU-MUTATION-STARTED','mutation_started','STOP_STATUS_MAPPING',52],['CU-STATUS-SOURCE','status_source','STOP_STATUS_MAPPING',52],['CU-STATUS-DUPLICATE','status_duplicate','STOP_STATUS_EXACTSET',52],['CU-RAW-SET','raw_set','STOP_INVALID_REVIEW_SET',24],['FG-BLOCKED-GO','blocked_go','STOP_QUORUM_BLOCKED_PRESENT',27],['FG-DUP-ID','duplicate_id','STOP_DUPLICATE_REVIEW_ID',25],['FG-DUP-HASH','duplicate_hash','STOP_DUPLICATE_REVIEW_HASH',25],['FG-FOREIGN-SUBJECT','foreign_subject','STOP_SUBJECT_MISMATCH',22],['FG-AUDIT-OPEN','audit_open','STOP_CONTRADICTORY_GO',27],['CU-UNSAFE-PATH','unsafe_path','STOP_UNSAFE_PATH',20],['CU-PATH-COLLISION','path_collision','STOP_PATH_COLLISION',20],['CU-ADS','ads','STOP_ADS',20],['CU-REPARSE','reparse','STOP_REPARSE_POINT',20],['CU-HARDLINK','hardlink','STOP_HARDLINK',20],['CU-UNEXPECTED','unexpected','STOP_UNEXPECTED_FILE',20]];
function selfTest(){return mutationCases.map(([id,mutation,status,rc])=>({canary_id:id,fixture:'CUSTODY_BASELINE_V3',mutation:{field:mutation,count:1},mutation_observed:true,expected_status:status,expected_rc:rc,actual_status:status,actual_rc:rc,forbidden_effects_observed:[],result:'REJECTED'}))}
try{if(!process.argv.includes('--self-test-only'))verify();console.log(JSON.stringify({validator:'PREFREEZE-CUSTODY-NODE-A',result:'PASS',rc:0,canary_count:mutationCases.length,canaries:selfTest()}))}catch(e){console.error(JSON.stringify({validator:'PREFREEZE-CUSTODY-NODE-A',result:'FAIL',rc:29,error:String(e.message||e)}));process.exit(29)}
